# FS_CFD_database
## General
This database is for Formula Student Aero guys struggling or enjoying their aero development.
It isn't easy to prove your Computational Fluid Dynamics (CFD) accuracy from technical, available resources and time points of view.
Especially in FS, where you need to make it by yourself, rather than just drawing your surface on screen, it is quite a challenging topic and probably some of you are about to give up the evaluation of your CFD result.
Therefore, I have decided to make a public database of CFD, for 10 m/s straight condition with up to 70M cells.
**Please be notified that this ReadMe is just a door, and all the data is stored in google drive, whose link is available later in this doc.**

## How to use this?
My expectation of usage of this data is shown as follows, but pretty much you can do as you want with this.
1. Run CFD with distributed CAD model for this simulation and make a comparison with provided database plots.
2. Or just enjoying staring at the beautiful photos

## Limitation of this data
70M cells sim result gives the most likely data within the range of this database but does not necessarily mean that this is accurate and true.
For valuable evaluation, the data should be compared with WT results, ideally quantitively as much as possible. 
Also, it is worth noting that the K-Omega SST model used here does not contain any specific modification for its separation region, so the turbulent viscosity around the separation region is likely less estimated.
In the presentation file, the 70M cells data is treated as reference data, but again, it is not assured that it is accurate enough.
Please find the data as the most accurate result within that database, more or less.

## Google Drive
Well, I am lazy enough not to put my effort into using GitHub properly. I don't know how to put a bunch of photo data into GitHub efficiently, as my local file is not linked with this repository, again sorry for my laziness.
But instead, I create a google drive and I am happy to put an invitation link for all of you guys.
- Raw data of CFD result, such as CpT plot or surface Cp plot: 

https://drive.google.com/drive/folders/1mf5Cxq2XfC3gGprzztVWZNoMcPCSArbq?usp=sharing
- Numerical graph generated by Matlab code: 

https://drive.google.com/drive/folders/1vYF1jgxsOkcHK8NPQzyqU2smVBAyfWsw?usp=sharing
- All codes for CpT contour converter, delta plot generator and Matlab graph generator:

https://drive.google.com/drive/folders/1yoeuZD6_OnBSm2FAL_QEOhWRNrElsWxB?usp=sharing
- Presentation：

https://docs.google.com/presentation/d/1yfOy6vDAZ8dyjhNIJWsjwiJqCvI9ZmI0/edit?usp=sharing&ouid=114974693398715275822&rtpof=true&sd=true

You can download the presentation file as follows. I strongly recommend downloading the PowerPoint version rather than PDF as some GIF files are missing in PDF.
![image](https://github.com/tagdtm/FS_CFD_database/assets/96266042/9cf2cd26-b17c-49d0-bc45-4f0f12558f31)

## Future Plan
- More cell number
- Tweak K-Omega SST with some NASA papers of better separation replication
- Try the GEKO model in Ansys fluent
- Install transition model into K-Omega SST
- Comparison between the Reynolds stress model
- Comparison with DES

## Request and contribution
If you have a specific request or you would like to contribute to this project, feel free to drop me an email at the address below.

yt7u21@soton.ac.uk
